// src/lib/components/SwitchInput/SwitchInput.svelte
<script lang="ts">
	import { Moon, Sun } from 'phosphor-svelte';

	export let checked: boolean;
	export let onchange: () => void;
</script>

<label class="switch">
	<input type="checkbox" class="switch__input" bind:checked {onchange} />
	<span class="switch__slider">
		{#if checked}
			<Moon size={14} weight="fill" />
		{:else}
			<Sun size={14} />
		{/if}
	</span>
</label>

<style>
	.switch {
		display: inline-flex;
		align-items: center;
		cursor: pointer;
		width: 24px;
		height: 24px;
		border-radius: 100px;
		border: 2px solid var(--toggle-button);
		position: relative;
	}

	.switch__input {
		opacity: 0;
		width: 0;
		height: 0;
		position: absolute;
	}

	.switch__slider {
		position: absolute;
		left: 2px;
		width: 1rem;
		height: 1rem;
		border-radius: 50%;
		background-color: var(--toggle-button);
		display: flex;
		align-items: center;
		justify-content: center;
		transition: transform 0.2s, background-color 0.3s;
		color: white;
	}

	.switch:active .switch__slider {
		transform: scale(0.9);
	}

	.switch:hover {
		border-color: var(--yellow-dark);
	}
</style>

// src/components/ui/SwitchInput/index.tsx

import { Moon, Sun } from "@phosphor-icons/react";
import styled from "styled-components";

const SwitchInput = styled.input`
  height: 0;
  width: 0;
  visibility: hidden;
`;

const SwitchLabel = styled.label`
  display: flex;
  align-items: center;
  justify-content: space-between;
  cursor: pointer;
  width: 2.5rem;
  height: 23px;
  border-radius: 100px;
  border: 2px solid ${props => props.theme['toggle-button']};
  position: relative;
  transition: background-color 0.5s;
`;

const SwitchButton = styled.span`
  content: "";
  position: absolute;
  top: 2px;
  left: 2px;
  width: 1.3rem;
  height: 20px;
  border-radius: 45px;
  transition: 0.5s;
  background: ${props => props.theme['toggle-button']};
  box-shadow: 0 0 2px 0 rgba(10, 10, 10, 0.29);
  ${SwitchInput}:checked + ${SwitchLabel} & {
    left: calc(100% - 2px);
    transform: translateX(-100%);
  }

  ${SwitchLabel}:active & {
    width: 25px;
  }
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
`;

interface SwitchInterface {
  id: string;
  toggled: boolean;
  onChange: () => void;
}

const Switch = ({ id, toggled, onChange } : SwitchInterface) => {
  return (
    <>
      <SwitchInput
        id={id}
        type="checkbox"
        checked={toggled}
        onChange={onChange}
      />
      <SwitchLabel htmlFor={id}>
        <SwitchButton>
          {toggled?<Moon color="#DBAC2C" weight="fill"/>:<Sun color="white"/>}
        </SwitchButton>
      </SwitchLabel>
    </>
  );
};

export default Switch;
